steps:
  - id: Test
    name: gcr.io/cloud-builders/gcloud
    script: |
      #!/usr/bin/env bash
      echo "$_FOO"
      echo "$(pwd)"
      ls -al

options:
  automapSubstitutions: true
  substitution_option: "ALLOW_LOOSE"
